#!/bin/sh

### BEGIN INIT INFO
# Provides:          reflex
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Controls a Reflex stats server (http://github.com/powdahound/reflex/)
### END INIT INFO

PLUGIN_NAME=reflex
PLUGIN_DIR=/var/reflex/server/reflex
PLUGIN_OPTS=""

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=`which twistd`
PIDFILE=/var/run/$PLUGIN_NAME.pid
DAEMON_OPTS="--umask=022 --pidfile=$PIDFILE --syslog --prefix=$PLUGIN_NAME $PLUGIN_NAME $PLUGIN_OPTS"

export PYTHONPATH=$PLUGIN_DIR

if [ ! -x $DAEMON ]; then
  echo "ERROR: Can't execute $DAEMON."
  exit 1
fi

if [ ! -d $PLUGIN_DIR ]; then
  echo "ERROR: Directory doesn't exist: $PLUGIN_DIR"
  exit 1
fi

start_service() {
  echo -n " * Starting $PLUGIN_NAME... "
  start-stop-daemon -Sq -p $PIDFILE -x $DAEMON -- $DAEMON_OPTS
  e=$?
  if [ $e -eq 1 ]; then
    echo "already running"
    return
  fi

  if [ $e -eq 255 ]; then
    echo "couldn't start :("
    return
  fi

  echo "done"
}

stop_service() {
  echo -n " * Stopping $PLUGIN_NAME... "
  start-stop-daemon -Kq -R 10 -p $PIDFILE
  e=$?
  if [ $e -eq 1 ]; then
    echo "not running"
    return
  fi

  echo "done"
}

case "$1" in
  start)
    start_service
    ;;
  stop)
    stop_service
    ;;
  restart)
    stop_service
    start_service
    ;;
  *)
    echo "Usage: /etc/init.d/$PLUGIN_NAME {start|stop|restart}" >&2
    exit 1   
    ;;
esac

exit 0
